---
driver_plugin: vagrant

driver_config:
  require_chef_omnibus: true
  #use_vagrant_provision: true
#  require_chef_omnibus: 10.26.0

platforms:
- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
    - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
    - recipe[apt]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: server
  run_list:
    - recipe[check_mk::server]
    - recipe[minitest-handler]
  attributes: {}
- name: agent
  run_list:
    - recipe[check_mk::agent]
    - recipe[minitest-handler]
    # - recipe[check_mk_test]
  attributes: {}
